version: '3.9'

services:
  wingman-db:
    image: zenfiric/wingman-sql:hello
    environment:
      POSTGRES_DB: ${DB_NAME:-devdb}
      POSTGRES_USER: ${DB_USER:-devuser}
      POSTGRES_PASSWORD: ${DB_PASS:-changeme}
    ports:
      - "5432:5432"
